# -*- coding: utf-8 -*-
"""Cyberbullying Detection using NLP and Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ixoZq-ECF7CVlnj2PlCG1pIHde853fr
"""

# Commented out IPython magic to ensure Python compatibility.

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
sns.set(style="darkgrid")

from google.colab import files
uploaded = files.upload()

# Load the CSV file (assumes it's in the same directory or uploaded to Colab)
df = pd.read_csv("Whatsapp_chat.csv")
df.head()

print("Columns in dataset:", df.columns.tolist())
print("\nNumber of messages:", len(df))
print("\nUnique senders:", df['names'].unique())

user_counts = df['names'].value_counts()
plt.figure(figsize=(8, 5))
sns.barplot(x=user_counts.index, y=user_counts.values, palette='viridis')
plt.title("Messages per User")
plt.ylabel("Number of Messages")
plt.xlabel("User")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x="hours", data=df, palette="magma")
plt.title("Messages by Hour of Day")
plt.xlabel("Hour")
plt.ylabel("Message Count")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x="days", data=df, palette="coolwarm")
plt.title("Messages by Day of the Month")
plt.xlabel("Day")
plt.ylabel("Message Count")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x="months", data=df, order=df["months"].unique(), palette="cubehelix")
plt.title("Messages by Month")
plt.xlabel("Month")
plt.ylabel("Message Count")
plt.tight_layout()
plt.show()

df['timestamp'] = pd.to_datetime(df['timestamp'])
daily_msgs = df.groupby('timestamp').size()

plt.figure(figsize=(12, 5))
daily_msgs.plot()
plt.title("Messages Over Time")
plt.xlabel("Date")
plt.ylabel("Number of Messages")
plt.tight_layout()
plt.show()